controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

    # config/routes.yaml
    user_register:
        path: /register
        controller: App\Controller\UserController::register

